# Yaml File Config 


httpServer:
      httpServerServer: "localhost"
      httpServerPort: "8080"
basicAutentication:
     basicAutenticationUsername: "admin"
     basicAutenticationPassword: "admin"


      

      